### ISSUE TITLE
Rendering engine does not account for changes in aspect ratio caused by the status bar

### ISSUE THREAD

**Issue by WoolieWool** [qbism/super8#2]
The renderer's aspect ratio correction seems to assume a fullscreen view, and only a fullscreen view. It does not account for changes in the size of the window caused by the status bar. vid_nativeaspect can adjust for this, but at the cost of some 2D image distortion and a constricted horizontal FOV.

http://i.imgur.com/w533tRC.png
Makaqu 1.4 (correct)

http://i.imgur.com/tj1P8t3l.png
Qbism super8, default settings except for fov 100 (badly stretched)

http://i.imgur.com/9QAqdi9.png
Qbism super8, vid_nativeaspect 2.01 (2D images appear perfect, view is slightly stretched, some FOV lost)

http://i.imgur.com/PTtfqOo.png
Qbism super8, vid_nativeaspect 2.23 (renderer proportions correct, 2D images compressed horizontally, major FOV loss)

**Comment by qbism** [comment]
Actually two things going on, both intentional I'm afraid...
"The renderer's aspect ratio correction seems to assume a fullscreen view, and only a fullscreen view."
This favors laptop native resolutions, some of which are weird. This is a benefit to some and annoyance to others but that's why vid_nativeaspect was created.

The other issue is FOV scaling, which actually comes from a later version of Makaqu.  Again this favors autodection of native aspect... when it works.  But again this can be overcome by manually increasing FOV

**Comment by qbism** [comment]
I've reopened this.  I see now that the view is getting 'squished' vertically when the statusbar background is on.

**Comment by qbism** [comment]
fixed in v238
